default_stages: [commit]

default_install_hook_types: [pre-commit, commit-msg]

ci:
  autoupdate_schedule: monthly
  # skip: [mypy]
  autofix_commit_msg: pre-commit auto-fixes
  autoupdate_commit_msg: pre-commit autoupdate

repos:
  # ruffのチェック
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.264"
    hooks:
      - id: ruff
        args: [--fix]

  # ruffで未対応の部分をblackで補完する
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [.]

  # mypyのチェック
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        exclude: ^tests/|^any-path/ # mypyの除外ディレクトリ。正規表現で記述できる
        additional_dependencies: [pydantic, types-PyYAML==6.0.7, types-requests, types-toml]


  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        stages: [commit, commit-msg]
        exclude_types: [html]
        additional_dependencies: [tomli] # needed to read pyproject.toml below py3.11

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.32.0
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
